version: '2'

services:
    static1:
        image: nginx:1.10
        ports:
            - "8081:80"
        volumes:
            - "./static_content_1:/usr/share/nginx/html:ro"
    static2:
        image: nginx:1.10
        ports:
            - "8082:80"
        volumes:
            - "./static_content_2:/usr/share/nginx/html:ro"
    static3:
        image: nginx:1.10
        ports:
            - "8083:80"
        volumes:
            - "./static_content_3:/usr/share/nginx/html:ro"
    nginx:
        image: nginx:1.10
        ports:
            - "8080:80"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
